# Generated by Django 3.2.8 on 2021-10-10 05:38

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия мероприятия')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(48.39786528867364, 54.3186259381731), srid=4326, verbose_name='Локация')),
                ('descriptions', models.TextField(max_length=100, verbose_name='Описания мероприятия')),
                ('radius', models.IntegerField(verbose_name='Радиус охвата события м.')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата и время оканчания мероприятия')),
                ('date_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время создания мероприятия')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятии',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='HumanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время заявки')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('video', models.FileField(null=True, upload_to='', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Сообщения от пользователя',
                'verbose_name_plural': 'Сообщении от пользователей',
                'ordering': ['-message'],
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField(verbose_name='Нобходимое количество волонтёров')),
                ('Message', models.TextField(verbose_name='Сообщение волонтёром')),
                ('datetime_need', models.DateTimeField(verbose_name='До какого срока необходимы волонтёры')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания мероприятия')),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_departments.events', verbose_name='Название мероприятия')),
            ],
            options={
                'verbose_name': 'Волонтёр',
                'verbose_name_plural': 'Волонтёры',
                'ordering': ['-Events'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=400, verbose_name='Заголовок сообщения')),
                ('title', models.TextField(verbose_name='Сообщение')),
                ('date_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время сообщения')),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_departments.events', verbose_name='Название мероприятия')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщении',
                'ordering': ['-header'],
            },
        ),
    ]
